name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 */4 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "472619563@qq.com"
          git config --local user.name "Yukuiii"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push

# 测试
  